import type { Assessment } from "./scraper"

export const mockAssessments: Assessment[] = [
  {
    name: "Verify G+ General Ability",
    url: "https://www.shl.com/solutions/products/verify-g-plus/",
    remoteTestingSupport: true,
    adaptiveSupport: true,
    duration: "24 minutes",
    testType: "Cognitive",
    description: "Measures critical reasoning through short verbal, numerical, and inductive reasoning questions.",
    keywords: ["reasoning", "cognitive", "verbal", "numerical", "inductive"],
  },
  {
    name: "Verify Coding",
    url: "https://www.shl.com/solutions/products/verify-coding/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "60 minutes",
    testType: "Technical",
    description: "Assesses programming skills in multiple languages including Java, Python, JavaScript, and SQL.",
    keywords: ["coding", "programming", "java", "python", "javascript", "sql"],
  },
  {
    name: "Occupational Personality Questionnaire (OPQ)",
    url: "https://www.shl.com/solutions/products/opq/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "25 minutes",
    testType: "Personality",
    description: "Measures workplace behavioral styles and preferences across 32 personality characteristics.",
    keywords: ["personality", "behavior", "workplace", "preferences"],
  },
  {
    name: "Verify Interactive",
    url: "https://www.shl.com/solutions/products/verify-interactive/",
    remoteTestingSupport: true,
    adaptiveSupport: true,
    duration: "30 minutes",
    testType: "Situational",
    description: "Assesses how candidates respond to realistic workplace scenarios through interactive simulations.",
    keywords: ["interactive", "simulation", "workplace", "scenarios", "situational"],
  },
  {
    name: "Verify Numerical Reasoning",
    url: "https://www.shl.com/solutions/products/verify-numerical/",
    remoteTestingSupport: true,
    adaptiveSupport: true,
    duration: "18 minutes",
    testType: "Cognitive",
    description: "Measures ability to analyze and interpret numerical data and make logical decisions.",
    keywords: ["numerical", "reasoning", "data", "analysis", "cognitive"],
  },
  {
    name: "Verify Verbal Reasoning",
    url: "https://www.shl.com/solutions/products/verify-verbal/",
    remoteTestingSupport: true,
    adaptiveSupport: true,
    duration: "17 minutes",
    testType: "Cognitive",
    description: "Assesses ability to evaluate written information and make logical decisions.",
    keywords: ["verbal", "reasoning", "written", "evaluation", "cognitive"],
  },
  {
    name: "Workplace Personality Inventory (WPI)",
    url: "https://www.shl.com/solutions/products/wpi/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "35 minutes",
    testType: "Personality",
    description: "Measures work styles and preferences related to job performance across various roles.",
    keywords: ["personality", "work", "styles", "preferences", "performance"],
  },
  {
    name: "Verify Python",
    url: "https://www.shl.com/solutions/products/verify-python/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "45 minutes",
    testType: "Technical",
    description: "Assesses proficiency in Python programming language through coding challenges.",
    keywords: ["python", "programming", "coding", "technical", "challenges"],
  },
  {
    name: "Verify Java",
    url: "https://www.shl.com/solutions/products/verify-java/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "45 minutes",
    testType: "Technical",
    description: "Evaluates Java programming skills through practical coding exercises.",
    keywords: ["java", "programming", "coding", "technical", "exercises"],
  },
  {
    name: "Verify SQL",
    url: "https://www.shl.com/solutions/products/verify-sql/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "40 minutes",
    testType: "Technical",
    description: "Tests SQL query writing and database manipulation skills.",
    keywords: ["sql", "database", "query", "technical", "data"],
  },
  {
    name: "Verify JavaScript",
    url: "https://www.shl.com/solutions/products/verify-javascript/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "45 minutes",
    testType: "Technical",
    description: "Assesses JavaScript programming skills including DOM manipulation and modern frameworks.",
    keywords: ["javascript", "programming", "dom", "frameworks", "technical"],
  },
  {
    name: "Motivation Questionnaire (MQ)",
    url: "https://www.shl.com/solutions/products/mq/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "20 minutes",
    testType: "Motivation",
    description: "Measures what motivates and energizes a person in a work environment.",
    keywords: ["motivation", "work", "energize", "preferences", "environment"],
  },
  {
    name: "Situational Judgement Test",
    url: "https://www.shl.com/solutions/products/sjt/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "30 minutes",
    testType: "Situational",
    description: "Evaluates judgment and decision-making in workplace scenarios.",
    keywords: ["situational", "judgment", "decision", "workplace", "scenarios"],
  },
  {
    name: "Remote Work Assessment",
    url: "https://www.shl.com/solutions/products/remote-work/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "25 minutes",
    testType: "Behavioral",
    description: "Assesses behaviors and preferences related to remote work effectiveness.",
    keywords: ["remote", "work", "behavior", "effectiveness", "virtual"],
  },
  {
    name: "Leadership Assessment",
    url: "https://www.shl.com/solutions/products/leadership/",
    remoteTestingSupport: true,
    adaptiveSupport: false,
    duration: "40 minutes",
    testType: "Leadership",
    description: "Evaluates leadership potential and competencies across various dimensions.",
    keywords: ["leadership", "potential", "competencies", "management", "executive"],
  },
]

